### ISSUE TITLE
BrowserSync not reloading changes

### ISSUE THREAD

**Issue by bigskillet** [Applelo/vite-plugin-browser-sync#16]
I'm running BrowserSync with `vite build --watch` and I can see the `script` injected into the page. I can also see the `Browsersync: connected` message when I manually reload the page, but it's not watching my changes. What am I missing?

```
export default {
  build: {
    outDir: 'dist',
    emptyOutDir: false,
    rollupOptions: {
      input: ['./src/main.js'],
      output: {
        entryFileNames: '[name].js',
        assetFileNames: '[name].[ext]'
      }
    }
  },
  plugins: [
    VitePluginBrowserSync({
      buildWatch: {
        enable: true,
        bs: {
          proxy: 'http://vite.valet',
          files: ['index.html']
        }
      }
    })
  ]
};
```

**Comment by Applelo** [comment]
Hi, you need to enable the `codeSync` option (check https://github.com/Applelo/vite-plugin-browser-sync?tab=readme-ov-file#vite-plugin-browser-sync-options-for-browsersync). I will address this in the next version to disable some overides made by the plugin on build watch.

**Comment by bigskillet** [comment]
That worked, thanks!

Are you saying `codeSync` can be removed in the next version?

**Comment by Applelo** [comment]
The `codeSync` option is set by [default to true by Browser sync](https://browsersync.io/docs/options#option-codeSync) but I override it because vitejs handles code refresh on dev. I forgot on `buildWatch` and `preview` to remove some overrides. 

So yes, in the next version you can keep `codeSync` set to `true` or remove it, it will do the same on `buildWatch`.
